#nginx:alpine registry.cn-hongkong.aliyuncs.com/xiefantasy/nginx:alpine
gogs/gogs:latest registry.cn-hongkong.aliyuncs.com/xiefantasy/gogs:latest
mysql:8.0 registry.cn-hongkong.aliyuncs.com/xiefantasy/mysql:8.0
redis:7.4 registry.cn-hongkong.aliyuncs.com/xiefantasy/redis:7.4
mongo:8.0 registry.cn-hongkong.aliyuncs.com/xiefantasy/mongo:8.0
jenkins/jenkins:latest registry.cn-hongkong.aliyuncs.com/xiefantasy/jenkins:latest
python:3.12.2-slim registry.cn-shanghai.aliyuncs.com/xiefantasy/python:3.12.2-slim
python:3.13.0-slim registry.cn-shanghai.aliyuncs.com/xiefantasy/python:3.13.0-slim
swarmpit/install:1.9 registry.cn-shanghai.aliyuncs.com/xiefantasy/swarmpit-install:1.9
swarmpit/swarmpit:latest registry.cn-shanghai.aliyuncs.com/xiefantasy/swarmpit:latest
couchdb:2.3.0 registry.cn-shanghai.aliyuncs.com/xiefantasy/couchdb:2.3.0
influxdb:1.8 registry.cn-shanghai.aliyuncs.com/xiefantasy/influxdb:1.8